use std::collections::hash_map::DefaultHasher;
use std::error::Error;
use std::fmt::{Display, Formatter};
use std::fs;
use std::hash::{Hash, Hasher};
use std::io;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub const CURRENT_CONFIG_SCHEMA_VERSION: u32 = 1;
pub const CURRENT_STORAGE_SCHEMA_VERSION: u32 = 1;

const SUNLIGHT_DIR: &str = ".sunlight";
const CONFIG_FILE: &str = "config.toml";
const GITIGNORE_FILE: &str = ".gitignore";

const AUTHORITATIVE_DIRS: &[&str] = &[
    "objects",
    "records",
    "topics",
    "operations",
    "views",
    "checkpoints",
    "executions",
    "conflicts",
    "export-map",
];

const LOCAL_ONLY_DIRS: &[&str] = &[
    "local",
    "cache",
    "projections",
    "tmp",
    "quarantine",
];

pub const GENERATED_GITIGNORE: &str = "\
# Generated by `sun init`.
# Sunlight treats Git as transport/export. Local state, caches, and raw
# execution payloads are ignored by default; policy-approved records remain
# visible for review.
/local/
/cache/
/projections/
/tmp/
/quarantine/
/index.sqlite
/executions/**/sandbox/
/executions/**/raw-logs/

# Object payloads are not globally ignored because policy may publish some of
# them. The engine must validate exact object reachability before committing or
# exporting.
";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositoryConfig {
    pub repository_id: String,
    pub config_schema_version: u32,
    pub storage_schema_version: u32,
    pub path_policy: PathPolicy,
    pub projection_policy: ProjectionPolicy,
    pub git_interop: GitInteropPolicy,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PathPolicy {
    pub case_sensitive: bool,
    pub unicode_normalization: String,
    pub symlinks: String,
    pub executable_bits: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionPolicy {
    pub default_root: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GitInteropPolicy {
    pub sunlight_commit_policy: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitReport {
    pub repo_root: PathBuf,
    pub sunlight_dir: PathBuf,
    pub repository_id: String,
    pub created_config: bool,
    pub created_gitignore: bool,
    pub created_directories: Vec<PathBuf>,
}

#[derive(Debug)]
pub enum RepositoryError {
    Io { path: PathBuf, source: io::Error },
    InvalidConfig { path: PathBuf, message: String },
}

impl Display for RepositoryError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(f, "failed to access {}: {}", path.display(), source)
            }
            Self::InvalidConfig { path, message } => {
                write!(f, "invalid Sunlight config at {}: {}", path.display(), message)
            }
        }
    }
}

impl Error for RepositoryError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::InvalidConfig { .. } => None,
        }
    }
}

impl RepositoryConfig {
    pub fn new(repository_id: String) -> Self {
        Self {
            repository_id,
            config_schema_version: CURRENT_CONFIG_SCHEMA_VERSION,
            storage_schema_version: CURRENT_STORAGE_SCHEMA_VERSION,
            path_policy: PathPolicy {
                case_sensitive: true,
                unicode_normalization: "preserve".to_string(),
                symlinks: "preserve".to_string(),
                executable_bits: "preserve".to_string(),
            },
            projection_policy: ProjectionPolicy {
                default_root: ".sunlight/projections".to_string(),
            },
            git_interop: GitInteropPolicy {
                sunlight_commit_policy: "conservative".to_string(),
            },
        }
    }

    pub fn to_toml(&self) -> String {
        format!(
            "\
repository_id = \"{}\"
config_schema_version = {}
storage_schema_version = {}

[path_policy]
case_sensitive = {}
unicode_normalization = \"{}\"
symlinks = \"{}\"
executable_bits = \"{}\"

[projection_policy]
default_root = \"{}\"

[git_interop]
sunlight_commit_policy = \"{}\"
",
            escape_toml(&self.repository_id),
            self.config_schema_version,
            self.storage_schema_version,
            self.path_policy.case_sensitive,
            escape_toml(&self.path_policy.unicode_normalization),
            escape_toml(&self.path_policy.symlinks),
            escape_toml(&self.path_policy.executable_bits),
            escape_toml(&self.projection_policy.default_root),
            escape_toml(&self.git_interop.sunlight_commit_policy),
        )
    }

    pub fn from_toml(input: &str, path: impl Into<PathBuf>) -> Result<Self, RepositoryError> {
        let path = path.into();
        let repository_id = parse_string_key(input, "repository_id").ok_or_else(|| {
            RepositoryError::InvalidConfig {
                path: path.clone(),
                message: "missing repository_id".to_string(),
            }
        })?;

        Ok(Self {
            repository_id,
            config_schema_version: parse_u32_key(input, "config_schema_version").unwrap_or(1),
            storage_schema_version: parse_u32_key(input, "storage_schema_version").unwrap_or(1),
            path_policy: PathPolicy {
                case_sensitive: parse_bool_key(input, "case_sensitive").unwrap_or(true),
                unicode_normalization: parse_string_key(input, "unicode_normalization")
                    .unwrap_or_else(|| "preserve".to_string()),
                symlinks: parse_string_key(input, "symlinks")
                    .unwrap_or_else(|| "preserve".to_string()),
                executable_bits: parse_string_key(input, "executable_bits")
                    .unwrap_or_else(|| "preserve".to_string()),
            },
            projection_policy: ProjectionPolicy {
                default_root: parse_string_key(input, "default_root")
                    .unwrap_or_else(|| ".sunlight/projections".to_string()),
            },
            git_interop: GitInteropPolicy {
                sunlight_commit_policy: parse_string_key(input, "sunlight_commit_policy")
                    .unwrap_or_else(|| "conservative".to_string()),
            },
        })
    }
}

pub fn init_repository(repo_root: impl AsRef<Path>) -> Result<InitReport, RepositoryError> {
    let repo_root = repo_root.as_ref().to_path_buf();
    let sunlight_dir = repo_root.join(SUNLIGHT_DIR);
    ensure_dir(&sunlight_dir)?;

    let mut created_directories = Vec::new();
    for child in AUTHORITATIVE_DIRS.iter().chain(LOCAL_ONLY_DIRS.iter()) {
        let path = sunlight_dir.join(child);
        if ensure_dir(&path)? {
            created_directories.push(path);
        }
    }

    let config_path = sunlight_dir.join(CONFIG_FILE);
    let (config, created_config) = if config_path.exists() {
        let body = read_to_string(&config_path)?;
        (
            RepositoryConfig::from_toml(&body, config_path.clone())?,
            false,
        )
    } else {
        let config = RepositoryConfig::new(generate_repository_id(&repo_root));
        write_new_file(&config_path, config.to_toml().as_bytes())?;
        (config, true)
    };

    let gitignore_path = sunlight_dir.join(GITIGNORE_FILE);
    let created_gitignore = if gitignore_path.exists() {
        false
    } else {
        write_new_file(&gitignore_path, GENERATED_GITIGNORE.as_bytes())?;
        true
    };

    Ok(InitReport {
        repo_root,
        sunlight_dir,
        repository_id: config.repository_id,
        created_config,
        created_gitignore,
        created_directories,
    })
}

fn ensure_dir(path: &Path) -> Result<bool, RepositoryError> {
    if path.is_dir() {
        return Ok(false);
    }

    fs::create_dir_all(path).map_err(|source| RepositoryError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(true)
}

fn read_to_string(path: &Path) -> Result<String, RepositoryError> {
    fs::read_to_string(path).map_err(|source| RepositoryError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn write_new_file(path: &Path, bytes: &[u8]) -> Result<(), RepositoryError> {
    fs::write(path, bytes).map_err(|source| RepositoryError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn generate_repository_id(repo_root: &Path) -> String {
    let mut hasher = DefaultHasher::new();
    repo_root.hash(&mut hasher);
    std::process::id().hash(&mut hasher);
    now_nanos().hash(&mut hasher);
    format!("repo-{:016x}", hasher.finish())
}

fn now_nanos() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default()
}

fn escape_toml(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn parse_string_key(input: &str, key: &str) -> Option<String> {
    let prefix = format!("{} = ", key);
    input.lines().find_map(|line| {
        let value = line.trim().strip_prefix(&prefix)?;
        let value = value.strip_prefix('"')?.strip_suffix('"')?;
        Some(value.replace("\\\"", "\"").replace("\\\\", "\\"))
    })
}

fn parse_u32_key(input: &str, key: &str) -> Option<u32> {
    let prefix = format!("{} = ", key);
    input.lines().find_map(|line| {
        line.trim()
            .strip_prefix(&prefix)
            .and_then(|value| value.parse::<u32>().ok())
    })
}

fn parse_bool_key(input: &str, key: &str) -> Option<bool> {
    let prefix = format!("{} = ", key);
    input.lines().find_map(|line| {
        line.trim()
            .strip_prefix(&prefix)
            .and_then(|value| value.parse::<bool>().ok())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_creates_architecture_aligned_layout() {
        let repo = TestRepo::new("layout");

        let report = init_repository(repo.path()).expect("init should succeed");

        assert!(report.created_config);
        assert!(report.created_gitignore);
        assert!(repo.path().join(".sunlight/config.toml").is_file());
        assert!(repo.path().join(".sunlight/.gitignore").is_file());

        for child in AUTHORITATIVE_DIRS.iter().chain(LOCAL_ONLY_DIRS.iter()) {
            assert!(
                repo.path().join(".sunlight").join(child).is_dir(),
                "missing .sunlight/{child}"
            );
        }

        let config = fs::read_to_string(repo.path().join(".sunlight/config.toml")).unwrap();
        assert!(config.contains("repository_id = \"repo-"));
        assert!(config.contains("sunlight_commit_policy = \"conservative\""));

        let gitignore = fs::read_to_string(repo.path().join(".sunlight/.gitignore")).unwrap();
        assert!(gitignore.contains("/local/"));
        assert!(gitignore.contains("/cache/"));
        assert!(gitignore.contains("/executions/**/raw-logs/"));
    }

    #[test]
    fn init_is_idempotent_and_preserves_identity_and_policy_files() {
        let repo = TestRepo::new("idempotent");

        let first = init_repository(repo.path()).expect("first init should succeed");
        let gitignore_path = repo.path().join(".sunlight/.gitignore");
        fs::write(&gitignore_path, "# user managed\n/local/\n").unwrap();

        let second = init_repository(repo.path()).expect("second init should succeed");

        assert!(!second.created_config);
        assert!(!second.created_gitignore);
        assert!(second.created_directories.is_empty());
        assert_eq!(first.repository_id, second.repository_id);
        assert_eq!(
            fs::read_to_string(gitignore_path).unwrap(),
            "# user managed\n/local/\n"
        );
    }

    struct TestRepo {
        path: PathBuf,
    }

    impl TestRepo {
        fn new(name: &str) -> Self {
            let mut path = std::env::temp_dir();
            path.push(format!(
                "sunlight-core-test-{}-{}",
                name,
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            fs::create_dir_all(&path).unwrap();
            Self { path }
        }

        fn path(&self) -> &Path {
            &self.path
        }
    }

    impl Drop for TestRepo {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }
}
